version: "3.9"

name: micro-ecommerce
services:
  catalog-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${CATALOG_ROOT_PASS}
      MYSQL_USER: ${CATALOG_USER}
      MYSQL_PASSWORD: ${CATALOG_USER_PASS}
      MYSQL_DATABASE: ${CATALOG_DB}
    env_file:
      - .env
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u$CATALOG_USER",
          "-p$CATALOG_USER_PASS",
          "-e",
          "SELECT 1;",
        ]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - micro-ecommerce_catalog-db:/var/lib/mysql
    ports:
      - "4001:3306"

  catalog-api:
    build:
      context: ./Services/Catalog
    depends_on:
      catalog-db:
        condition: service_healthy
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${CATALOG_DATABASE_URL}
    volumes:
      - ./Services/Catalog/src:/app/src

  client:
    build:
      context: ./Web
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      CATALOG_API_URL: ${CATALOG_API_URL}
    volumes:
      - ./Web:/app

volumes:
  micro-ecommerce_catalog-db:
    external: true
