version: "3.4"

name: micro-ecommerce
services:
  catalog-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${CATALOG_ROOT_PASS}
      MYSQL_USER: ${CATALOG_USER}
      MYSQL_PASSWORD: ${CATALOG_USER_PASS}
      MYSQL_DATABASE: ${CATALOG_DB}
    env_file:
      - .env
    restart: always
    volumes:
      - catalog-db:/var/lib/mysql
    ports:
      - "4001:4001"

  catalog-api:
    build:
      context: ./Services/Catalog
    depends_on:
      - catalog-db
    ports:
      - "3001:3001"
    volumes:
      - ./Services/Catalog/src:/app/src

  client:
    build:
      context: ./Web
    ports:
      - "3000:3000"
    volumes:
      - ./Web/pages:/app/pages
      - ./Web/styles:/app/styles
      - ./Web/public:/app/public

volumes:
  catalog-db:
