version: "3.4"

services:
  catalog-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${CATALOG_ROOT_PASS}
      MYSQL_USER: ${CATALOG_USER}
      MYSQL_PASSWORD: ${CATALOG_USER_PASS}
      MYSQL_DATABASE: ${CATALOG_DB}
    env_file:
      - .env
    restart: always
    ports:
      - "4001:3306"

  catalog-api:
    build:
      context: ./Services/Catalog
    depends_on:
      - catalog-db
    ports:
      - "3001:3306"

  client:
    build:
      context: ./Web
    ports:
      - "3000:3000"
