version: "3.9"

name: micro-ecommerce
services:
  api-gateway:
    build:
      context: ./ApiGateway
    env_file:
      - .env
    environment:
      CART_API_URL: ${CART_API_URL}
    ports:
      - "3004:3004"
    volumes:
      - ./ApiGateway/src:/app/src

  cart:
    image: redis:alpine
    ports:
      - "3003:3003"

  catalog-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${CATALOG_ROOT_PASS}
      MYSQL_USER: ${CATALOG_USER}
      MYSQL_PASSWORD: ${CATALOG_USER_PASS}
      MYSQL_DATABASE: ${CATALOG_DB}
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u$CATALOG_USER",
          "-p$CATALOG_USER_PASS",
          "-e",
          "SELECT 1;",
        ]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - micro-ecommerce_catalog-db:/var/lib/mysql
    ports:
      - "4001:3306"

  cart-api:
    build:
      context: ./Services/Cart
    ports:
      - "3002:3002"
    depends_on:
      - cart
    volumes:
      - ./Services/Cart/src:/app/src
    env_file:
      - .env

  catalog-api:
    build:
      context: ./Services/Catalog
    depends_on:
      catalog-db:
        condition: service_healthy
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${CATALOG_DATABASE_URL}
    volumes:
      - ./Services/Catalog/src:/app/src

  user-api:
    build:
      context: ./Services/User
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${USER_DATABASE_URL}
    volumes:
      - ./Services/User/src:/app/src

  user-db:
    image: mysql:8.0
    volumes:
      - ./Services/User/src/database/seed:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_ROOT_PASS}
      MYSQL_USER: ${USER_USER}
      MYSQL_PASSWORD: ${USER_USER_PASS}
      MYSQL_DATABASE: ${USER_DB}
    env_file:
      - .env
    ports:
      - "4002:3306"

  client:
    build:
      context: ./Web
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    env_file:
      - .env
    environment:
      API_GATEWAY_URL: ${API_GATEWAY_URL}
    volumes:
      - ./Web:/app

volumes:
  micro-ecommerce_catalog-db:
    external: true
